#!/usr/bin/env python3
"""
Standalone Auto-Audit script.
Runs OUTSIDE Streamlit to avoid rerun lifecycle issues.

Reads:
  /tmp/audit_context.txt     — strategy metrics text
  /tmp/audit_pine_source.txt — original Pine Script (optional)

Writes:
  /tmp/audit_status.txt      — progress status (polled by Streamlit)
  /tmp/audit_results.json    — final results (loaded by Streamlit)

Launched by Streamlit as a background subprocess.
"""
import subprocess, shutil, json, re, os, sys

CONTEXT_FILE = "/tmp/audit_context.txt"
PINE_FILE = "/tmp/audit_pine_source.txt"
RESULTS_FILE = "/tmp/audit_results.json"
STATUS_FILE = "/tmp/audit_status.txt"

def write_status(msg):
    with open(STATUS_FILE, "w") as f:
        f.write(msg)

def parse_recommended_params(text):
    """Extract recommended_params JSON block from AI reply."""
    patterns = [
        r'```json:recommended_params\s*\n(.*?)```',
        r'```json\s*:?\s*recommended_params\s*\n(.*?)```',
        r'```recommended_params\s*\n(.*?)```',
    ]
    for pat in patterns:
        match = re.search(pat, text, re.DOTALL)
        if match:
            try:
                return json.loads(match.group(1).strip())
            except json.JSONDecodeError:
                continue
    # Fallback: any JSON block with all-numeric values
    for match in re.finditer(r'```json\s*\n(.*?)```', text, re.DOTALL):
        try:
            parsed = json.loads(match.group(1).strip())
            if isinstance(parsed, dict) and all(isinstance(v, (int, float, bool)) for v in parsed.values()):
                return parsed
        except json.JSONDecodeError:
            continue
    return None

def auto_merge_pine(pine_source, params):
    """Apply AI-recommended parameter changes to Pine Script source."""
    lines = pine_source.splitlines()
    changes = []

    for pname, pval in params.items():
        for i in range(len(lines)):
            old_line = lines[i]
            if pname not in old_line:
                continue
            if not re.search(r'input\.(int|float|bool)\s*\(', old_line):
                continue

            if 'input.bool' in old_line:
                str_val = 'true' if pval else 'false'
                new_line = re.sub(
                    r'(input\.bool\s*\()\s*(true|false)',
                    r'\g<1>' + str_val,
                    old_line, count=1, flags=re.IGNORECASE)
            else:
                new_line = re.sub(
                    r'(input\.(?:int|float)\s*\()\s*[-]?[\d.]+',
                    r'\g<1>' + str(pval),
                    old_line, count=1)

            if new_line != old_line:
                lines[i] = new_line
                changes.append(f"Line {i+1}: {pname} → {pval}")

    if not changes:
        return None, []

    revised = "\n".join(lines)
    change_summary = "\n".join([f"// {c}" for c in changes])
    revised = (
        f"// ══════════════════════════════════════════════════════════\n"
        f"// AUTO-AUDIT REVISED — {len(changes)} parameter changes applied\n"
        f"// Generated by Just Trades AI Quant Analyst\n"
        f"// ══════════════════════════════════════════════════════════\n"
        f"{change_summary}\n"
        f"// ══════════════════════════════════════════════════════════\n\n"
        + revised
    )
    return revised, changes

def main():
    write_status("loading context")

    if not os.path.exists(CONTEXT_FILE):
        write_status("error: no context file found")
        return

    with open(CONTEXT_FILE, "r") as f:
        context = f.read()

    # Read Pine Script source if available
    pine_source = None
    if os.path.exists(PINE_FILE):
        with open(PINE_FILE, "r") as f:
            pine_source = f.read().strip()
        if not pine_source:
            pine_source = None

    write_status("calling AI (this may take a few minutes)...")

    system_prompt = """You are an elite institutional quantitative analyst AND strategy engineer. You diagnose problems AND prescribe exact fixes with specific parameter changes.

FORMATTING RULE: When writing dollar amounts, write 'USD X' not '$X'.

MANDATORY OUTPUT: At the END of your analysis, include a JSON block with recommended parameter changes:
```json:recommended_params
{
  "Parameter Title": new_value
}
```
Only include parameters you want to CHANGE. Use exact parameter TITLE strings. Values must be numbers."""

    user_prompt = (
        "FULL AUTO-AUDIT — analyze this strategy completely:\n"
        "1. Grade (A-F) with composite score\n"
        "2. Top 5 weaknesses with SPECIFIC fixes (line numbers, before/after)\n"
        "3. Expected improvement for each fix\n"
        "4. Risk assessment\n\n"
        "Include the ```json:recommended_params``` block at the end.\n\n"
        "STRATEGY DATA:\n" + context
    )

    full_prompt = system_prompt + "\n\n[USER]\n" + user_prompt + "\n\n[ASSISTANT]\n"

    # Try Claude CLI
    claude_bin = shutil.which('claude') or '/usr/local/bin/claude'
    reply = None

    if not os.path.exists(claude_bin):
        write_status(f"error: claude CLI not found at {claude_bin}")
        return

    try:
        result = subprocess.run(
            [claude_bin, '--output-format', 'text', '--max-turns', '1'],
            input=full_prompt,
            capture_output=True, text=True, timeout=600,
            cwd=os.path.dirname(os.path.abspath(__file__))
        )
        if result.returncode == 0 and result.stdout.strip():
            reply = result.stdout.strip()
            write_status(f"AI done ({len(reply)} chars), processing results...")
        else:
            stderr_msg = (result.stderr or '')[:300]
            write_status(f"error: CLI returned {result.returncode}: {stderr_msg}")
            return
    except subprocess.TimeoutExpired:
        write_status("error: AI timed out after 10 minutes")
        return
    except Exception as e:
        write_status(f"error: {e}")
        return

    # Parse recommended params
    params = parse_recommended_params(reply)

    # Auto-merge Pine Script if we have source + params
    revised_pine = None
    changes_made = []
    if pine_source and params:
        write_status("applying parameter changes to Pine Script...")
        revised_pine, changes_made = auto_merge_pine(pine_source, params)
        if revised_pine:
            # Append the revised pine to the AI reply for display
            reply += (
                "\n\n---\n\n## Complete Revised Pine Script\n\n"
                "```pine:revised_strategy\n" + revised_pine + "\n```"
            )

    # Save results
    output = {
        "reply": reply,
        "params": params,
        "revised_pine": revised_pine,
        "changes_made": changes_made,
        "status": "complete",
    }

    with open(RESULTS_FILE, "w") as f:
        json.dump(output, f)

    write_status("complete")
    print(f"Done! Reply: {len(reply)} chars, Params: {list((params or {}).keys())}, "
          f"Pine changes: {len(changes_made)}")


if __name__ == "__main__":
    main()
